Fix appscreener parser (#7077)
* Update parser.py

Error, when trying to parse appscreener report. 

[05/Nov/2022 01:41:15] ERROR [dojo.engagement.views:683] invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/app/./dojo/engagement/views.py", line 668, in import_scan_results
    test, finding_count, closed_finding_count, _ = importer.import_scan(scan, scan_type, engagement, user, environment, active=active, verified=verified, tags=tags,
  File "/app/./dojo/importers/importer/importer.py", line 298, in import_scan
    parsed_findings = parser.get_findings(scan, test)
  File "/app/./dojo/tools/solar_appscreener/parser.py", line 50, in get_findings
    finding.line = int(finding.line)
ValueError: invalid literal for int() with base 10: ''

Because first line transfer to string after split. This fix should resolve it. I checked - all ok.

* Update parser.py

* Update parser.py

* Update parser.py

* Update parser.py

* Fix error: ValueError: invalid literal for int() with base 10: ''

* Update parser.py

Flake8 fix

Co-authored-by: Damien Carol <damien.carol@gmail.com>