Fix JIRA integration
Currently, pushing to JIRA fails the following exception in the Celery
worker.  Fix this by re-adding the check whether a `JIRA_Issue` object
exists for the `Finding` or `Engagement`.

```
DoesNotExist('JIRA_Issue matching query does not exist.',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/defectdojo/django-DefectDojo/dojo/tasks.py", line 235, in update_issue_task
    update_issue(find, old_status, push_to_jira)
  File "/home/defectdojo/django-DefectDojo/dojo/utils.py", line 1064, in update_issue
    j_issue = JIRA_Issue.objects.get(finding=find)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
Exception: JIRA_Issue matching query does not exist.
```