Update helper.py
I have observed that when a finding is deleted manually, the code is failing with Nonetype error.
AttributeError: \'NoneType\' object has no attribute \'hash_code\'\n', 'args': '(92882,)', 

Verifying if finding does not exist checks if the finding was deleted then the functions returns.