Add unittests as a travis job
add unittest travis file

update unittest script

Add sudo and --user option

update unittest script

add chromedriver install to script

update script

update chromedriver install script

correct script for chromedriver

adjust permission mode for chromedriver

fix calling chmod without sudo

Add chrome selenium headless option to product unittests

Add google chrome binary

Add code to setup admin user and password environment variables

adjust script

readjust script

adjust test script and server ports in products

update script

update script

update script

update script

update script

update test files and add to travis unittest

comment out tests not ready and add check to exit if any test fails

replace deprecated method

replace deprecated method

Testing fail

Testing fail

update all unit tests with if condition

Add express option to add jira configs

Appease accesslint bot

Remove JIRA status if product is not configured

fix initial date format

Add wait time to test_add_product_finding_test

comment out product unit test from script

testing a very long wait time

testing a very long wait time

try remove headless from engagement test

Try out my page load wait function

make some changes

make some changes

update file load option in engagement import scan test

update file load option in engagement import scan test

update file load option in engagement import scan test

update change

adjust unitest

try out dev activation in script

Correct overlooked error in #1498

Add table of contents to HTML/Asciidoc reports

Return dedupe to a "working" state

Return close_old_findings

Delete setup.bash

This is the old setup.bash. New one is in the setup folder. Removing to disable confusion.

enhanced blackduck parser

fixing flake8 errors

[wip] to squash. unittest failing locally bc it seems it does not recognize the
zipfile.

increase filepath to 4000 varchar to hold bigger paths concatenation

Use Python 3.5-compatible code

adding .zip extension to choose report file from

Fix unit tests and syntax errors

Check subtype of report object and cast if necessary

In-app doc update

change file name and dep order

remove old file name

Fix Jira status bug

Fix product manager displays

Added option to set caption for finding images

Add option to move engagements to different products

Update migrations to make builds happy

BUGFIX: The test summary table in the engagement view displays the name of the engagement lead in each row instead of the test lead. This PR changes this UI bug so that the name of the test lead in the row "Lead" will appear.

Manually set parent of duplicate

Include description in filter

Correct duplicate options display

Add test name to dropdown

Trying again with some print out

Add fix for test_image_add error

add recursive to file permission on django dockerfile

add recursive to file permission on django dockerfile

MOdify docker file to create media folder

MOdify docker file to create media folder2

Add sudo to python3 calls

checking out sudo

rearrange users

adjust selenium

update python3 version

giving virtulenv a try

adjust dockerfile

modify docker file again

move docker compose into script

comment out user1001 in dockerfilenginx nd django

Add some os user management to script and docker file

Add virtualenv

Trying python within container

add selenium

fix python

adding full script

adding full script

try stuff

Added google chrome addon to travis

add -f install to travis

running build with docker-compose

trying out unit_test docker-compose override

Defect Dojo/SonarQube integration

Reverted f-Strings, replace them with String.format

Reverted f-Strings, replace them with String.format

Fixing AttributeError: module 're' has no attribute 'RegexFlag'

Flake8 fix

Updated finding page to show SonarQube transition history

Updated finding page to show SonarQube transition history

Renumbered migration to 0011 after latest dev merge

Fix for SonarQube versions with no Security Hotspot support

Rebuild migration after pulling upstream/dev

SonarQube integration suggestions pending to implement

Fixing accesslint

Renamed migrations after merging upstream/dev

Fix flake8 error

Updated migration to solve mysql case insensitive issue
Added a temp rule cache in SonarQube client to import findings faster

Update and rename 0017_sonarqube_api_integration.py to 0018_sonarqube_api_integration.py

Bump django from 2.2.1 to 2.2.4

Bumps [django](https://github.com/django/django) from 2.2.1 to 2.2.4.
- [Release notes](https://github.com/django/django/releases)
- [Commits](https://github.com/django/django/compare/2.2.1...2.2.4)

Signed-off-by: dependabot[bot] <support@github.com>

adjust finding status to display product metrics

oversight fix + no verified filter for open_finding

Signed-off-by: Fred Blaise <fred.blaise@gmail.com>

remove unique contraint from jira_id

add missing volumes in docker dev mode

Fix bug when displaying accepted findings

If the cwe is None (which is the default), displaying the accepted finding will throw a type error. This is a relict form the python 3 migration: https://docs.python.org/3/whatsnew/3.0.html#ordering-comparisons

on behalf of DB Systel GmbH

urlunsplit crash if no path is specified

json_output doesnt exist

v1 aqua parser

Signed-off-by: Fred Blaise <fred.blaise@protonmail.com>

promote_to_finding crash on endpoints

Make finding images downloadable via API

FEATURE: Adds an alert box to add_template.html to the delete template button  to confirm the deletion.
BUGFIX: Force the validation check for required input fields

fix bug with jumping sidebar

The sidebar jumps down if you hover over it. Now the sidebar remains on the top.

On behalf of DB System GmbH

API Filter Enhancements for engagements

Added title and engagement to Test object API filters

Fix Flake8

Manually merged DefectDojo master and Development

added on delete cascade for note_type foreign key

Removed urlresolvers

Editing a note modified with note types

Changed the code to match PEP8 standards

Added unit tests for note types

Added missing aria-labels

Moved db changes to a separate file

Report generation modified with note-types

Improved report generation changes

Fixed the conflicts in db migrations files

Resolve conflicts in comments.html file

Fix tables of contents and test pdf report

Allow for newlines in notes

Fix whitesource parser

The whitesource parser fails if the report does not contain all information. Now it will using an empty default value instead.

On behalft of DB Systel GmbH

fix introduced regression

Signed-off-by: Fred Blaise <fred.blaise@protonmail.com>

add external relationnal db support

Update configmap.yaml

typo

typo

weird config map behavior

chqnge postgresql secret name

typo

fixes #1566 add unittest and try-catch.

issue_1542 fix - Using dynamic secret name

Checkmarx API enhancements

Convert tabs to spaces

Add ability to import OWASP Dependency Track Finding Packaging Format (FPF) Exports as a scan

Trim whitespace

Fix flake8 issues

Add Dependency Track parser to test_types fixture

Updates to Dojo fidning title and description to accomodate for optional fields from Dependency Track

Updates to JSON file parsing to accomodate for Django file wrapper vs normal Python File objects

Resolve conflicts with other test type that was added to dev branch

Update test_type.json

Fix issue #1576 and #1577

add product unit test

Fix flake8 issues

go back to installing and setting up chrome browser from unittest script

Update unit tests to reflect all new changes

Update unit tests to reflect all new changes

comment out engagement unittest

remove excess import scan test

Implement Azure AD Tenant OAuth. Fix #1307

As more and more enterprises are leveraging Office 365 and Azure,
implementing Azure AD authentication using OAuth would be extremely
helpful as an alternative from relying on AD/LDAP connectivity, enabling
admins to deploy Defect Dojo in the cloud without having to send
authentication requests back to on-premises AD/LDAP.

This implementation is based on social-core, building upon the
pre-existing OKTA and Google integration.

ptvsd debug option

Incorporating @ptrovatelli's suggestions.

make flake8 happy

increase strip from 20 to 200 chars

Introducing DataTables to Products and Findings

Separating product tags into their own column:
Product tags were added just to the right of the product name. this made very difficult to properly export as CSV or Excel in the upcoming DataTables effort, so splitting the tags which provide relevant information in their own column was the most efficient route to support DataTables export

Introducing DataTables to Products and Findings

Removing DataTables from node package as it is not working, but adding static files.

Added DataTables to Products and Findings html pages to support better sorting, filtering and exporting.

Remove sorting and exporting from DataTables on non relevant fields

Checkboxes and action fields should not be sortable nor exportable, which this commit addresses for Product and Findings list view

Adding the All Engagements View

Dojo menu had a "All Engagements" entry, but it opened Active Engagements only.

This commit still respects the Active Engagements but introduces the All Engagements view

DataTables now available on All Engagements

Introducing support for DataTables for all engagements view

Remove sorting and exporting from DataTables on non relevant fields

Checkboxes and action fields should not be sortable nor exportable, which this commit addresses for All Engagements view

Improve Product view filtering

Include additional fields that can be used for filtering the product view

fix finding.cwe in filters

Add Note Create and Delete to Api V2 Finding Endpoint

Adjust Flake inconsistencies

Handle error when no note found

Fix flake8

add sed script to change user id from 1001 to 1000 before building container

fix css selector for import button

remove unused import

update user id sed script and also uncomment dedupe test"

Clean up unittest by removing excess debug print logs

Remove Survery Fixture

Make foxtures run on install

Trying thigs

Configure survey presentation on dojo side

Finishing touches on the dojo side

Change migration name before pulling current dev

Change dependency as well

Change dependency as well

Add finding ID, Eng. Version and tags to search results. Fixes #1559

On the simple search results, adding new column to contain the Finding ID (Dojo ID) and also include engagement version and engagements tag under the engagement column.

Fixes #1559

Update migrations to mesh with dev branch

Revert a silly merge mistake

remove index and replace with keys

adding channel origin id to model, and take either one

restored processing of single security.csv file. Re-enabled unittests
for csv. Added extra file for new security.csv header format.

Fixed wrong column name for csv title processing

Fixed property name

Fix Import OpenVas Scan Result

Issues:
OpenVas Scan Result were not imported.

Solution:
Adapt the code for python 3
We've edit dojo/tools/openvas_csv/parser.py , now it is able to import the scan without a 500 error and with the Findings.

clean up debug code

Fix Tab Issues

To much space

Fix Flake8 errors to resolve premature approval

Update issue templates

mrod-updating-serializer

mrod-updating-model

mcr-fixingProductList

mcr-fixingProductList

Fix Flake8 errors

Transition Finding from Mitigated using Jira doesn't remove Mitigated status

Manage Manual Changes in SonarQube

adjust docker-compose build and run in script

use release image docker-compose override